--ALTER SCHEMA public OWNER TO postgres;
--
--GRANT ALL ON SCHEMA public TO postgres;
--
--ALTER DEFAULT PRIVILEGES IN SCHEMA public
--GRANT ALL ON TABLES TO postgres;
--
--ALTER DEFAULT PRIVILEGES IN SCHEMA public
--GRANT ALL ON SEQUENCES TO postgres;

--DROP TABLE IF EXISTS employees;
--DROP TABLE IF EXISTS products;
--DROP TABLE IF EXISTS orders;
--DROP TABLE IF EXISTS flyway_schema_history;

CREATE TABLE employees (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    dept VARCHAR(50)
);

CREATE TABLE products (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100),
    price DECIMAL(10,2)
);

CREATE TABLE orders (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_date DATE,
    amount DECIMAL(10,2)
);

commit;